efault: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: reserve_development

test:
  <<: *default
  database: reserve_test

production:
  <<: *default
  database: reserve_production
